<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>6e62af39-0bde-4839-a96a-2cccbde8b5c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[4]/div/div/ul[2]/li[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.login-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06122f52-473a-4d78-a2c6-ed1af54ca1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-link</value>
      <webElementGuid>44ccd7f7-ba98-44fd-ad49-0aff92edbda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그아웃</value>
      <webElementGuid>e5f20090-bd8d-41de-bac5-aefcc5f629c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header is-student open-menu is-desktop has-current-learn is-run-page&quot;]/nav[@class=&quot;header-wrap&quot;]/div[@class=&quot;header__mymenu is-on&quot;]/div[@class=&quot;header__mymenu-dropdown t-main-content-box is-on&quot;]/div[@class=&quot;header__mymenu-wrap&quot;]/ul[@class=&quot;header__mymenu-info&quot;]/li[@class=&quot;logout bottom&quot;]/a[@class=&quot;login-link&quot;]</value>
      <webElementGuid>344ed1ca-cbe3-41c7-ae1a-cf859b5a3471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[4]/div/div/ul[2]/li[8]/a</value>
      <webElementGuid>94b17cea-0879-445f-82b3-fc9e6709e640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그아웃')]</value>
      <webElementGuid>5af5e18e-9ca1-46d2-b2e4-ec6d56db91ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>60e4c48e-83d8-4240-8dce-b12cbe7475a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '로그아웃' or . = '로그아웃')]</value>
      <webElementGuid>c25aa499-6ca4-4f2b-9e72-93a2fd3aa456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
