<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_close-btn</name>
   <tag></tag>
   <elementGuidId>caf63032-1bad-4329-b84b-c894312a4929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='student']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.close-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae8d336e-955f-4ade-9148-1134c3bfab74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-btn</value>
      <webElementGuid>044c03b4-cf94-4355-9451-e25beff4c853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student&quot;)/div[@class=&quot;learn-header&quot;]/div[@class=&quot;learn-header-wrap&quot;]/div[@class=&quot;close-btn&quot;]</value>
      <webElementGuid>44ea9011-4d84-4127-b4a2-d4dd3e630606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='student']/div/div/div</value>
      <webElementGuid>3b0cb9d9-adb6-491e-9442-9352f374e104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>c1ec0702-4cac-4158-bdd8-4f7912668599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
