<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_chooseProduct</name>
   <tag></tag>
   <elementGuidId>2174abb7-b543-4478-bad9-10a42897cd1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pro-loop--link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@class, 'pro-loop--link')])[${index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73183524-ce1b-4a0e-be20-6c2b6d4931c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/ao-polo-nam-jacquard-aristino-aps207sah2</value>
      <webElementGuid>88139cc5-29e9-41a3-852a-8ee1d867fca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pro-loop--link</value>
      <webElementGuid>c9aa6282-0b96-430c-b77e-8879d436b07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-page&quot;)/div[@class=&quot;collection-wrapper&quot;]/div[@class=&quot;collection-body&quot;]/div[@class=&quot;container-fluid p8&quot;]/div[@class=&quot;d-flex flex-wrap push-section&quot;]/div[@class=&quot;results-section&quot;]/div[@class=&quot;filter-wrapper--grid ajax-render&quot;]/div[@class=&quot;grid-products&quot;]/div[@class=&quot;pro-tile pro-loop pro-t1 1&quot;]/div[@class=&quot;pro-loop--wrap&quot;]/div[@class=&quot;pro-loop--head&quot;]/a[@class=&quot;pro-loop--link&quot;]</value>
      <webElementGuid>e26e95ea-99ed-47bf-8500-7cd3ae37e92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-page']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>e0f0cdc3-2e50-4e99-bed1-11eecdda4240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/ao-polo-nam-jacquard-aristino-aps207sah2')]</value>
      <webElementGuid>c9c42e36-ceed-42a6-acb1-32b4dd2d4ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>ea618e7c-a6e5-4a72-9625-7b01c20c4ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/ao-polo-nam-jacquard-aristino-aps207sah2']</value>
      <webElementGuid>525ee409-73d9-4c66-8b64-48e9f3d323c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
