<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_addToCart</name>
   <tag></tag>
   <elementGuidId>a74f3544-3004-4ad5-81ab-97cfe8a2b658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-addtocart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-addtocart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ace7de16-dcb9-4956-b0bb-3645ba770c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60aed792-802e-4733-bcb6-52539dec10f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-addtocart</value>
      <webElementGuid>ee4c2a90-5a4c-45a6-bd5d-06735a10dd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn add-cart</value>
      <webElementGuid>6e931715-2161-4980-8132-0d4d4542bae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>fbfcd68d-e34e-471c-ab18-a2cedd0f814d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-addtocart&quot;)</value>
      <webElementGuid>86f183e8-a0e3-4122-959c-7fdbdc90c992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-addtocart']</value>
      <webElementGuid>900012f5-22e3-41ad-a528-1e6249709dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productdetail-page']/div/div/div/div/div[2]/div[2]/div[6]/div[2]/button</value>
      <webElementGuid>21d2b755-7fc1-4dba-a7a2-3b82b60b7aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXL'])[1]/following::button[3]</value>
      <webElementGuid>e1ec5c8f-0240-4d60-8560-9e11a76c56be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/following::button[3]</value>
      <webElementGuid>c198861e-af0e-4279-9ff2-34f17f3b52d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời gian giao hàng dự kiến'])[1]/preceding::button[2]</value>
      <webElementGuid>6886f414-56ec-4543-889e-ca3f7bd9752b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/button</value>
      <webElementGuid>41f27a6e-74ac-4e07-b890-6620ba045cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-addtocart' and (text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>a983b60a-7add-4804-9018-e95588a1963a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
