<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_closeCart</name>
   <tag></tag>
   <elementGuidId>55970195-ab14-43d1-a908-b552c22ae5d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close-sidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='minicart']/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;minicart&quot;)/div[@class=&quot;sidebar-nav&quot;]/div[@class=&quot;sidebar-head&quot;]/button[@class=&quot;close-sidebar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb61075a-27e0-4b1d-8fce-4ed37bf83175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-sidebar</value>
      <webElementGuid>e10aa22f-9c8f-4905-ae21-e2a310268912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minicart&quot;)/div[@class=&quot;sidebar-nav&quot;]/div[@class=&quot;sidebar-head&quot;]/button[@class=&quot;close-sidebar&quot;]</value>
      <webElementGuid>390a4d43-179f-46e4-b7fa-5434e474c631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart']/div/div/button</value>
      <webElementGuid>041daf66-a712-4a30-9e3b-2d091289d4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi cho chúng tôi'])[1]/following::button[1]</value>
      <webElementGuid>a288fe71-9a86-447c-939c-4b281f4d93e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chưa có sản phẩm nào trong giỏ hàng'])[1]/preceding::button[1]</value>
      <webElementGuid>ed943d11-24dd-4579-b89f-5001edf33274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền hàng'])[1]/preceding::button[1]</value>
      <webElementGuid>facb8cad-397f-4049-809c-7df655ff03c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button</value>
      <webElementGuid>dee987eb-a8e4-4fc5-9ce3-d728a552ec86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
