<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SUPPORT_inputSearchAuto</name>
   <tag></tag>
   <elementGuidId>00c1e88b-4128-4af6-8385-74f4bd002bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputSearchAuto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSearchAuto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Bạn cần tìm gì?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54e2b3b7-b0f1-44c3-ba4f-494805326bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSearchAuto</value>
      <webElementGuid>b02d0ff3-7862-4e60-8188-9bdbf7b7b997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control searchform-input</value>
      <webElementGuid>fa7ade06-fc22-4dbc-abe0-13588110f192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>86eabe77-e757-48b8-b041-4669f9b33622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d6949ead-5b83-4fcb-ad92-e251be79a013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1e87d1a-8168-4e57-8469-5f3b81fc64e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7d2270da-bad5-4184-9fe4-fba46e3646c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn cần tìm gì?</value>
      <webElementGuid>37b110b0-3b70-4db4-9cb6-adea8cdd60a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSearchAuto&quot;)</value>
      <webElementGuid>63a73a26-b5f3-4074-a328-ce82d046f0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSearchAuto']</value>
      <webElementGuid>8553f7a1-bfca-4c4f-a52c-7d03f5297aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchform']/div/input</value>
      <webElementGuid>c1270b1f-c5ac-4cbe-a10d-f400a23e6289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1466f314-fb0d-4aa9-8950-3f799e3b14b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputSearchAuto' and @name = 'q' and @type = 'text' and @placeholder = 'Bạn cần tìm gì?']</value>
      <webElementGuid>3a39f3e8-2734-429c-a0ac-86f16e0cb6d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
