<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>open_miniCart</name>
   <tag></tag>
   <elementGuidId>7e8d0b4d-194d-49e1-bc2e-355673d7df2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-click-cartmini</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-click-cartmini']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cecfcfa-6a11-4c73-9cd2-fc5ba9f25dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>77e0a765-04c7-4e93-b0ae-7b3338cf810c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasitem</value>
      <webElementGuid>e79d829e-9357-4a83-a010-6907e29ee662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-click-cartmini</value>
      <webElementGuid>3a26b7d6-7562-4a65-9391-986f85e517b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									
									0 
								</value>
      <webElementGuid>ce0f1161-40e5-43a7-96d4-8e0c7ecb1636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-click-cartmini&quot;)</value>
      <webElementGuid>9f3e62ad-7986-42f7-baa5-8da38d782c2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='js-click-cartmini']</value>
      <webElementGuid>4813eeed-e457-4f32-88dc-b5d26969ec2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='mainHeader']/div/div/div/div[3]/div/ul/li[4]/a</value>
      <webElementGuid>3efeac96-92d2-48ae-a3ff-acbf1b9f6c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARISTINO'])[1]/following::a[5]</value>
      <webElementGuid>b287b929-28e8-470e-8afb-6305f871332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUPPORT'])[1]/following::a[7]</value>
      <webElementGuid>9dc070a8-e953-401f-9f0c-eedc4dd050e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/preceding::a[3]</value>
      <webElementGuid>622a56fe-e103-4ac5-9104-b76c97928c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANG PHỤC'])[1]/preceding::a[3]</value>
      <webElementGuid>825c2308-0e01-4fa4-96e9-b9afca84cfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>a2e731e3-954f-4918-bc5e-af8ea7ca1587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>2ab1acae-f8b1-4d75-bca3-5b846344d98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'js-click-cartmini' and (text() = '
									
									0 
								' or . = '
									
									0 
								')]</value>
      <webElementGuid>36a0139e-e202-4ccb-aa72-8f50695af5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
