<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_PriceTotal</name>
   <tag></tag>
   <elementGuidId>fe13c821-49de-4ee0-a398-6628894f30a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minicart .total-price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='minicart-subtotal']/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;minicart-subtotal&quot;)/div[@class=&quot;number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d834f49-202c-4d50-8599-240688ea3271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>55fdc30d-b32c-41af-ae29-b98fdad2103a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1,190,000₫</value>
      <webElementGuid>cfaddfa3-0bb7-43fe-8a9c-4915672fbbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minicart-subtotal&quot;)/div[@class=&quot;number&quot;]</value>
      <webElementGuid>c78a5b28-0e9c-4abe-a6db-f8cd8c3c4185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart-subtotal']/div[2]</value>
      <webElementGuid>bcd166c7-0c67-45e6-a489-28d481c4912d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền hàng'])[1]/following::div[1]</value>
      <webElementGuid>0a5be3b2-bde5-4ba3-9207-1e9027d2dcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Short Thể Thao Nam In Aristino ASO800AAH2'])[3]/following::div[15]</value>
      <webElementGuid>61fd0bb4-4ca8-44d8-a171-94fb94b7221d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phí vận chuyển'])[1]/preceding::div[1]</value>
      <webElementGuid>a7df34c7-924e-43a6-8e74-9c0b0edc9065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giảm giá'])[1]/preceding::div[4]</value>
      <webElementGuid>8961bb0d-397a-4440-85ca-1e33c0305c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div/div[2]</value>
      <webElementGuid>9e2ea1c7-2e56-4fbd-91cb-e5e7e30dcccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1,190,000₫' or . = '1,190,000₫')]</value>
      <webElementGuid>82b90b41-b7e5-4423-81fb-f50d9ddc45ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
