<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_quantityonCart</name>
   <tag></tag>
   <elementGuidId>7942bade-27e3-439a-a81c-34e6fd5f1b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minicart input.item-quantity-mini</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>	</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'updates[]' and @id = 'updates_1164838513']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>056124b5-77e3-4e77-9cd3-cd1e612902cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vid</name>
      <type>Main</type>
      <value>1164838513</value>
      <webElementGuid>c78abf4a-8181-4467-9ce2-09ba1351b4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b82e07bc-5ed6-4a1d-a414-a3db8724131f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product</name>
      <type>Main</type>
      <value>1072691307</value>
      <webElementGuid>22eb003c-c5ad-4eb2-990a-d8cf83f6c926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8132520-dbc8-47ef-9744-194aa00ba80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>682d272b-e923-40f8-b57e-afab8931a83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updates[]</value>
      <webElementGuid>eaeddbd6-75aa-41fd-a257-18bca6574e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2a64cf38-e4a9-42f2-a4e6-986dc86d0548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updates_1164838513</value>
      <webElementGuid>5863604f-5510-4cef-9291-bdb1ff1275da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>89500000</value>
      <webElementGuid>1ee469a0-af9a-4fd4-9dff-6ef3a056c679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>25e17752-d6f4-40a1-946c-abc7bbdef4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc line-item-qty item-quantity-mini</value>
      <webElementGuid>de884658-4c71-4d25-8723-1a06a0a4e65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updates_1164838513&quot;)</value>
      <webElementGuid>3cf2d9bc-4490-44fa-bb16-1b2cd3744d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='updates_1164838513']</value>
      <webElementGuid>cb3b5072-4164-4d4d-b6dd-e0abb3573899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart']/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>ffcced93-1f84-4ace-b1b7-8c8706390bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>88fc2296-47f2-4aa3-bafa-ea4b6fa346fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'updates[]' and @id = 'updates_1164838513']</value>
      <webElementGuid>7eb1a3ce-8b86-4b49-9184-023ee5594e9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
