<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>a1cfacba-300f-4d08-982e-001fbdd98e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[2]/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51521254-7e97-458f-85ea-48b59fda7be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manager</value>
      <webElementGuid>89e501fc-dfb5-499d-8514-2d75bf7882b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>마이페이지</value>
      <webElementGuid>5be0f86d-4372-4b80-9e26-7b24d7428538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header brand-header&quot;]/nav[@class=&quot;brand-header__wrap&quot;]/div[@class=&quot;brand-header__menu&quot;]/ul[1]/li[7]/a[1]</value>
      <webElementGuid>1db26692-9226-4ef9-b05d-c84caffaec50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[2]/ul/li[7]/a</value>
      <webElementGuid>d63094d6-5a8b-48af-b6e5-096a750efefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'마이페이지')]</value>
      <webElementGuid>b8c4fcb8-0625-44f0-ad00-0ab74ed04297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manager')]</value>
      <webElementGuid>b41b125e-3cf9-4eb4-a26f-2f68700c5351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>4c9ffa2e-b06f-441f-b3b3-e1897e2a5765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manager' and (text() = '마이페이지' or . = '마이페이지')]</value>
      <webElementGuid>e475b1e4-9bf7-436a-89c6-e43eac42a8a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
