<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_joyquebon.com</name>
   <tag></tag>
   <elementGuidId>8d2539a4-8ead-44e9-902e-39045a1a040a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newMyPage']/div[2]/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.account</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91b0e185-94c9-49aa-a0d5-f0488af055b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>19ecffd1-b538-44a3-9d55-01c6c01f7ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>joy@quebon.com</value>
      <webElementGuid>4bb067b8-3046-4886-8696-7edd74337708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newMyPage&quot;)/div[@class=&quot;mypage-container&quot;]/div[@class=&quot;user-info-wrap&quot;]/span[@class=&quot;account&quot;]</value>
      <webElementGuid>851f868d-2ef2-4128-90bb-3aee1ae2c216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newMyPage']/div[2]/div/span[2]</value>
      <webElementGuid>6f23439d-dbc4-4fbe-9f69-523d06491cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]</value>
      <webElementGuid>0c51059a-0b1e-486b-b633-9e51e14cd81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'joy@quebon.com' or . = 'joy@quebon.com')]</value>
      <webElementGuid>0273d8d5-6bc3-464b-8648-8359729fdb98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
