<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>b39295a9-4e1d-41b6-9b9d-0477b375948d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[4]/div/div/ul[2]/li[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.login-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b227b3ba-25bc-4891-99fd-593d8e228f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-link</value>
      <webElementGuid>d3d4bfa3-77b8-40ee-9423-235f99471335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그아웃</value>
      <webElementGuid>361827ba-69bf-4092-92c9-575e94e7245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header is-student open-menu is-desktop&quot;]/nav[@class=&quot;header-wrap&quot;]/div[@class=&quot;header__mymenu is-on&quot;]/div[@class=&quot;header__mymenu-dropdown t-main-content-box is-on&quot;]/div[@class=&quot;header__mymenu-wrap&quot;]/ul[@class=&quot;header__mymenu-info&quot;]/li[@class=&quot;logout bottom&quot;]/a[@class=&quot;login-link&quot;]</value>
      <webElementGuid>333bddd8-3892-429b-af9c-3db073caee6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[4]/div/div/ul[2]/li[8]/a</value>
      <webElementGuid>64c32735-2f44-4f56-bcb7-f0fb586f572b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그아웃')]</value>
      <webElementGuid>9c5d4ef3-2bc9-498d-9b51-530b02af21fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>fa9b159e-bad9-401e-9f84-c7e7f4361184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '로그아웃' or . = '로그아웃')]</value>
      <webElementGuid>1172a869-4425-4f7f-9817-3d0c87d87c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
