<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>a48ed540-eb2d-4abf-9ddc-01017d992613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.log</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1f091da-9e5d-41c7-9100-979caaa46203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>log</value>
      <webElementGuid>8354012d-9238-4243-8cfb-7b119336df72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그인</value>
      <webElementGuid>96de1d58-9d5e-4570-b033-fab5186e40c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header brand-header main-header&quot;]/div[@class=&quot;quick-menu is-out is-bottom-btn&quot;]/div[@class=&quot;quick-menu-wrap&quot;]/span[@class=&quot;log&quot;]</value>
      <webElementGuid>b6a71310-c8dc-4f05-970d-545fe30aa1cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/span</value>
      <webElementGuid>8af124fa-352d-467b-a012-a7be8867d91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>b2ecbd69-e43e-43e3-be07-bae408d82b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '로그인' or . = '로그인')]</value>
      <webElementGuid>2b84a7a8-bdcf-4edb-8f35-78412cacd6bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
