<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>58a46f15-3d48-48df-ab40-e365ba69986d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.brand-header_btn__3uSbU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>531443f7-8f21-4df5-9a85-fbc007b340f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-header_btn__3uSbU</value>
      <webElementGuid>da681d63-a9b6-46f7-9032-6cd755c884c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>e310dcb2-006f-477b-80fd-7621d7afc836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그인</value>
      <webElementGuid>32dc0707-1120-4599-a9cf-f516e0b98996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;brand-header_header-wrap__3Q5R3&quot;]/div[@class=&quot;brand-header_header-container__2BBIJ&quot;]/div[@class=&quot;brand-header_user-menus__1a9Uu&quot;]/a[@class=&quot;brand-header_btn__3uSbU&quot;]</value>
      <webElementGuid>6deaba88-6119-492f-b2bf-85a5e92a7344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/a</value>
      <webElementGuid>e21642da-ab0c-40ef-8cd1-579897ff1e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그인')]</value>
      <webElementGuid>e04c4d7b-22d6-4f29-8b0c-ccfcb668d762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login')]</value>
      <webElementGuid>36a5ae1f-148c-4001-b00e-8880e61689cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>cdcfe23e-93ee-4af1-ba4c-94077f71a7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login' and (text() = '로그인' or . = '로그인')]</value>
      <webElementGuid>eeb73ff0-f417-4840-a2a9-5bf1a72771a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
