<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>9ad945f6-8a81-42f5-a858-7134be8a331d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>827ecd00-2115-4333-813e-e750401b5cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow flex-shrink-0 h-full bg-yellow rounded-2xl bg-no-repeat bg-center flex justify-center items-center flex-col [box-shadow:inset_0px_-4px_0px_rgba(0,0,0,0.1)]</value>
      <webElementGuid>28f5a0e7-473c-4d5c-bc48-ba2e6a50b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/library</value>
      <webElementGuid>c1d28c5a-c009-43f3-9f26-ee0ba982a0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>도서관</value>
      <webElementGuid>7060dd54-50e7-4a15-8a00-d3adb390129b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full min-h-screen bg-[#F2F8FD] flex pb-[160px] md:pb-[120px]&quot;]/div[@class=&quot;relative max-w-[1200px] bg-[#F2F8FD] flex flex-col gap-4 md:gap-0 md:flex-row pt-24 w-full mx-auto px-6&quot;]/div[@class=&quot;flex flex-col flex-grow&quot;]/div[@class=&quot;flex items-center gap-4 mt-4 h-[182px]&quot;]/a[@class=&quot;flex-grow flex-shrink-0 h-full bg-yellow rounded-2xl bg-no-repeat bg-center flex justify-center items-center flex-col [box-shadow:inset_0px_-4px_0px_rgba(0,0,0,0.1)]&quot;]</value>
      <webElementGuid>4852be3c-c98d-4110-a9b1-04fdc2d7f035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/a</value>
      <webElementGuid>350901d7-0aeb-46e1-8194-eae35c0f9f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/library')]</value>
      <webElementGuid>e9e453aa-dd74-4e94-ab80-0c89faa05cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6e077f10-e88f-4cbf-a253-376b946931e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/library' and (text() = '도서관' or . = '도서관')]</value>
      <webElementGuid>8f76f107-72cf-4ab2-8be5-feba91a340a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
