<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>43d1c7f9-3126-4d55-836a-35ef7d213e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;깨봉샵&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>360ebbf5-ecf3-4a5c-998b-ff14f2d19440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>깨봉샵</value>
      <webElementGuid>8791ff5b-8515-41f9-a910-cecbb6827751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/icon-color-shop.svg</value>
      <webElementGuid>e4ed05ca-92d2-487d-904a-a621525d60e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6ea7e8a1-17b3-4fc1-9f71-cd6ce3bb1762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f2823b19-e8c7-4a99-835b-e1346535b0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6ec6f3f0-1645-4897-83b3-f7b57ce0cabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4ec2f773-8cd6-4b84-a0ea-833a9b936e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>32909d51-fb0b-4399-9888-623b9894709c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full min-h-screen bg-[#F2F8FD] flex pb-[160px] md:pb-[120px]&quot;]/div[@class=&quot;relative max-w-[1200px] bg-[#F2F8FD] flex flex-col gap-4 md:gap-0 md:flex-row pt-24 w-full mx-auto px-6&quot;]/div[@class=&quot;flex flex-col flex-grow&quot;]/div[@class=&quot;flex items-center gap-4 mt-4 h-[182px]&quot;]/a[@class=&quot;flex-grow flex-shrink-0 h-full bg-purple rounded-2xl bg-no-repeat bg-center flex justify-center items-center flex-col [box-shadow:inset_0px_-4px_0px_rgba(0,0,0,0.1)]&quot;]/img[1]</value>
      <webElementGuid>d93f54a9-e607-4ecb-b7b9-e3debc9bebcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/a[3]/img</value>
      <webElementGuid>bc1e4a65-6f8d-4187-ad85-ed5f35c52380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='깨봉샵']</value>
      <webElementGuid>89b4d882-b466-45ca-8b47-1cbcc0148d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>fcc8a8b3-d44e-4fe3-b104-201d58224674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '깨봉샵' and @src = '/assets/icon-color-shop.svg']</value>
      <webElementGuid>581fd63b-c57e-4325-a2c7-93330d0fe668</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
