<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3</name>
   <tag></tag>
   <elementGuidId>9aa976e2-ddc2-4ad4-9f4d-a5fd8d7a6604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;놀이터&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>80623d46-0207-45c4-9fff-86d73e3039df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>놀이터</value>
      <webElementGuid>39aee217-f9a4-4c16-a089-3c14c7936334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/icon-color-game.svg</value>
      <webElementGuid>d77d035d-8a63-4d2d-bc30-4ee93f4672d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c8c21adc-f3a6-420e-8417-cb61c6b75e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>0cf3b20c-a8e1-48eb-b85e-4b650cde5f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b24ac10e-2711-471f-a08a-a039a39a923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dc07af82-7dd4-44d0-823f-e0f639f95f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>60de85a7-c426-45b8-8016-13e0f3e9d920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full min-h-screen bg-[#F2F8FD] flex pb-[160px] md:pb-[120px]&quot;]/div[@class=&quot;relative max-w-[1200px] bg-[#F2F8FD] flex flex-col gap-4 md:gap-0 md:flex-row pt-24 w-full mx-auto px-6&quot;]/div[@class=&quot;flex flex-col flex-grow&quot;]/div[@class=&quot;flex items-center gap-4 mt-4 h-[182px]&quot;]/a[@class=&quot;flex-grow flex-shrink-0 h-full bg-blue rounded-2xl bg-no-repeat bg-center flex justify-center items-center flex-col [box-shadow:inset_0px_-4px_0px_rgba(0,0,0,0.1)]&quot;]/img[1]</value>
      <webElementGuid>7f790865-08a3-4208-8505-247258418cf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[3]/a[2]/img</value>
      <webElementGuid>ce84bebe-c38d-496e-b204-4e82cc5a4f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='놀이터']</value>
      <webElementGuid>4ff281fb-0476-433f-ad65-5c1f0f53875f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>18a04380-a261-40b7-89ed-92e49296bf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '놀이터' and @src = '/assets/icon-color-game.svg']</value>
      <webElementGuid>84e444d2-026c-465f-b8cd-e571480c34fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
