<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>fff91f2b-22c5-4276-9dfa-6d053eb048f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;icon-coin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c737e8df-a267-4b8f-bdba-a756d3ced906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-coin</value>
      <webElementGuid>58df89d7-4be1-4f7d-a44b-b94cbcf189a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/icon-color-coin.svg</value>
      <webElementGuid>ceb3dc4f-98e2-4912-825b-6f13a552a243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c2a6f999-39d8-445c-8bf3-938393cce6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>16e80a6d-a4c9-4641-a01f-10b4d1c1f065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f681a897-66c3-4a02-a4cb-93c4650b5f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-yellow&quot;]/div[@class=&quot;max-w-[1200px] flex items-center w-full h-24 gap-4 p-6 mx-auto&quot;]/div[@class=&quot;relative flex items-center flex-shrink-0 h-full gap-2 pl-4 pr-2 bg-white shadow-md cursor-pointer group rounded-2xl&quot;]/div[@class=&quot;relative w-8 h-8 cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>e638228f-ba1d-46ad-9370-bd031b116641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/img</value>
      <webElementGuid>bd7d7506-d5b4-4321-bfa8-ab65fd711a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon-coin']</value>
      <webElementGuid>56d62249-4460-4953-8c6a-7c5a7a8544f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>57f56b55-57ef-4d96-b3d0-6c419d2c1bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-coin' and @src = '/assets/icon-color-coin.svg']</value>
      <webElementGuid>6728ec79-bc4d-442a-9e72-056b7decaa78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
