<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>31f72ded-4895-4e0e-af1f-5bebf8d14d62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/a/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.brand-header_logo-text__1IOsa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>75c4f08a-56e0-4f34-9a05-d2ff8544a525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-header_logo-text__1IOsa</value>
      <webElementGuid>c2a9fb88-87b1-45f4-929a-6dd1c8846781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>인공지능 세상을 살아갈 사람들의 수학</value>
      <webElementGuid>03385f75-c00d-40cc-81ea-f4f69e8991c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;brand-header_header-wrap__3Q5R3&quot;]/div[@class=&quot;brand-header_header-container__2BBIJ&quot;]/a[@class=&quot;brand-header_logo-wrap__ns4og&quot;]/p[@class=&quot;brand-header_logo-text__1IOsa&quot;]</value>
      <webElementGuid>e77aca4f-b6ec-41a3-af80-a3ff7a50466a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/a/p</value>
      <webElementGuid>d2fa9d03-c362-4f46-8beb-c3273cef6bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>38a22fd0-2002-4241-9eb8-abf6d6ea8eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '인공지능 세상을 살아갈 사람들의 수학' or . = '인공지능 세상을 살아갈 사람들의 수학')]</value>
      <webElementGuid>9469e85e-2ef3-455e-b4fa-9ee75db6d0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
