<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_w-8 h-8 stroke-2px mx-auto text-white</name>
   <tag></tag>
   <elementGuidId>4faa5870-4007-4740-9948-d03c8a1697df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9bc9915e-8422-4a8c-9993-86fb8e3ef2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>ec9969b8-97fa-48b4-8bb4-a1ca0ef628a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9d36dba1-1170-46e7-87bd-96b78cbb75f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c303fc0d-701f-4fd1-90a7-ff959ff12dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>13530517-3e44-421c-b4eb-9a6328acf6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>c5660503-ad9b-4844-93c7-d65e78f19d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>06382a65-18bd-403a-ba46-96ad3cae6533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-8 h-8 stroke-[2px] mx-auto text-white</value>
      <webElementGuid>ecc4f756-ce61-4e35-9e56-f30c74121f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>6d197793-6e5c-4363-8c08-dd820352954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>e7bd635e-b498-407d-ac93-bac54e2b407d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>a2cd9f1d-b1a0-4522-abfc-1a71c50e85f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex flex-col min-h-screen overflow-auto gap-8 px-8 pt-6 bg-no-repeat bg-lightBlue-200&quot;]/div[@class=&quot;relative flex items-center justify-start flex-shrink-0 w-full max-w-[1200px] mx-auto&quot;]/div[@class=&quot;flex items-center justify-between flex-shrink-0 w-full&quot;]/div[@class=&quot;flex items-center justify-center gap-4&quot;]/button[@class=&quot;flex items-center w-12 h-12 shadow-md bg-orange rounded-2xl&quot;]/svg[@class=&quot;w-8 h-8 stroke-[2px] mx-auto text-white&quot;]</value>
      <webElementGuid>951afce9-81ee-4572-b4e6-9b0fc930edb8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
