<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Where we flyOpens Modal</name>
   <tag></tag>
   <elementGuidId>0def307f-e0a7-40a4-8417-6fcd8cd5f5ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.actionable.actionable_button.actionable_informational.button.icon-links--button.check-fares-form--bottom-icon-links_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionable actionable_button actionable_informational button icon-links--button check-fares-form--bottom-icon-links_button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Where we fly Opens Modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swa-content&quot;)/div[1]/div[2]/div[@class=&quot;container container_large air-low-fare-calendar-index-page&quot;]/section[@class=&quot;section&quot;]/div[@class=&quot;background&quot;]/div[@class=&quot;container container_standard&quot;]/div[@class=&quot;form-container index-page--form-container&quot;]/form[@class=&quot;form air-low-fare-calendar-check-fares-form air-low-fare-calendar-check-fares-form_expanded-size&quot;]/div[@class=&quot;check-fares-form--bottom&quot;]/ul[@class=&quot;air-informational-links check-fares-form--bottom-informational-links&quot;]/li[@class=&quot;informational-links--item informational-links--item_where-we-fly&quot;]/div[@class=&quot;modal-trigger&quot;]/button[@class=&quot;actionable actionable_button actionable_informational button icon-links--button check-fares-form--bottom-icon-links_button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swa-content']/div/div[2]/div/section/div/div[2]/div/form/div[8]/ul/li/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now accepting reservations through November 05, 2021.'])[1]/following::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/button</value>
   </webElementXpaths>
</WebElementEntity>
