<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opens new window. External site which _33a3c4</name>
   <tag></tag>
   <elementGuidId>0fd0999d-c2fb-46df-bb10-0998cb9f7172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FlyoutTrigger_6']/div/div/div/div/div/div/ul/li[3]/a/span[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.link-column.link-column_primary.header-flyout--column > li.link-column--link > a.actionable.actionable_link.actionable_external-link.actionable_suffix.actionable_dark.link > span.swa-icon.swa-icon_micro.actionable--icon.actionable--icon_suffix.actionable--icon_small-gap.swa-icon_external-link-box > span.swa-icon--icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swa-icon--icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlyoutTrigger_6&quot;)/div[@class=&quot;overlay-container--content-wrapper&quot;]/div[@class=&quot;overlay-container--content&quot;]/div[@class=&quot;overlay-container--flyout-content&quot;]/div[@class=&quot;header-flyout header-flyout_extended&quot;]/div[@class=&quot;header-flyout--content-section&quot;]/div[1]/ul[@class=&quot;link-column link-column_primary header-flyout--column&quot;]/li[@class=&quot;link-column--link&quot;]/a[@class=&quot;actionable actionable_link actionable_external-link actionable_suffix actionable_dark link&quot;]/span[@class=&quot;swa-icon swa-icon_micro actionable--icon actionable--icon_suffix actionable--icon_small-gap swa-icon_external-link-box&quot;]/span[@class=&quot;swa-icon--icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlyoutTrigger_6']/div/div/div/div/div/div/ul/li[3]/a/span[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/ul/li[3]/a/span[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlyoutTrigger_5']/div/div/div/div/div/div/ul[2]/li[2]/a/span[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span[3]/span</value>
   </webElementXpaths>
</WebElementEntity>
