<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_</name>
   <tag></tag>
   <elementGuidId>e9252b7c-9c8a-4188-9e99-3975268a0ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b006f827-8b68-4d7b-88a7-6d8942438589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-tab__nav</value>
      <webElementGuid>7d8da88c-70f1-4274-bfa3-ceadce1f6547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>학부모</value>
      <webElementGuid>fb9b5a4f-2e87-4038-b23f-2e135f5dcb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;content brand is-desktop&quot;]/div[@class=&quot;login new&quot;]/ul[@class=&quot;login-tab&quot;]/li[@class=&quot;login-tab__nav&quot;]</value>
      <webElementGuid>7a3f8d2e-7cbc-464f-b7f1-ce09d4226381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/ul/li[2]</value>
      <webElementGuid>e34d03fb-ac57-4df4-8044-303cbb351370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]</value>
      <webElementGuid>eb3d9959-e92e-49da-9e82-e3f8fc915254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '학부모' or . = '학부모')]</value>
      <webElementGuid>8e96f8eb-debe-4eae-8d68-68b7926854c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
