<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>0fd29b46-209c-4af1-9189-7dfe1d276617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.log</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1656caa-6217-4f1e-aa2e-c459cb8ec9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>log</value>
      <webElementGuid>8b6becb8-20ee-4810-8de9-8dd96e1bb764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그인</value>
      <webElementGuid>9c98360b-c8c2-411d-8fb9-7e09d11bed02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header brand-header main-header&quot;]/div[@class=&quot;quick-menu is-out is-bottom-btn&quot;]/div[@class=&quot;quick-menu-wrap&quot;]/span[@class=&quot;log&quot;]</value>
      <webElementGuid>656dd6f8-9ab7-48d8-9d7e-0642351d7c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/span</value>
      <webElementGuid>31a7e70c-5ccf-4961-a392-268abd777ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>99e2f42f-e2c6-403a-a059-6ed7f932fea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '로그인' or . = '로그인')]</value>
      <webElementGuid>8ee852d7-117d-4493-a0b4-30578b1ed489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
